---
- hosts: ios
  gather_facts: no  # Disable default fact gathering
  tasks:
    - name: Gather Cisco IOS facts
      cisco.ios.ios_facts:
        gather_subset: all
      register: device_facts # Store collected facts in a variable

    - name: Display collected device facts
      debug:
        msg: "{{ device_facts }}"
