---
- hosts: ios     
  tasks:


  # Network To Code module to grab inventory data
  - name: Show Inventory
    ntc_show_command:
      connection: "{{ connection }}"
      platform: "{{ platform }}"
      port: "{{ port }}"
      command: 'show inventory'
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: results

  - debug: var=results.response

  - name: Bundle data in a new hash, but only if Serial is not blank.
    set_fact:
     inventory: "{{ inventory|default([]) + [ {'hostname': ansible_net_hostname, 'ip': inventory_hostname, 'name': item.descr, 'serial': item.sn, 'version': ansible_net_version } ] }}"
    with_items: "{{ results.response }}"
    when: item.sn != ''

  #- name: Debug Check if you want
  #  debug: var=inventory

  # Write Headers for Cisco My Devices - hostname,IP,ProductID,serial
  - name: Write mydevices.csv
    run_once: true
    shell: echo Serial Number,Device Name,Tags,Notes > mydevices.csv
    with_items: "{{ inventory }}"

  - name: Write My Devices CSV File
    shell: 'echo {{ item.serial }},{{ item.hostname }},"IP-"{{ item.ip }} "|" "IOS-{{ item.version }}", >> {{ path_prefix }}mydevices.csv'
    with_items: "{{ inventory }}"
