---
- hosts: ios
  gather_facts: no
  tasks:
  - name: backup ios config
     ios_config:
       backup: yes
       backup_options:
         filename: "running-config.txt"
         dir_path: "/data/{{ inventory_hostname }}"

