---
- hosts: ios
  gather_facts: no


  tasks:
  - name: get timestamp
     command: date +%Y%m%d-%H-%M-%S
     register: timestamp
  - name: backup ios config
     ios_config:
       backup: yes
       backup_options:
         filename: "running-config-{{ timestamp.stdout }}"
         dir_path: "/data/{{ inventory_hostname }}"

