---
- hosts: ios
    tasks:

# Gather Ansible Facts About Access #
    - name: Gather Ansible Facts About Access
      ios_facts:
        gather_subset:
          - all

# Print facts on screen #          
    - debug: 
        msg: "{{ ansible_facts }}"
